name: Deploy Lambda Function

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: my-lambda-function
  ZIP_FILE_NAME: lambda_function.zip

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt -t .

    - name: Package Lambda function
      run: zip -r9 $ZIP_FILE_NAME .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --zip-file fileb://$ZIP_FILE_NAME \
          --region $AWS_REGION
