name: Deploy Lambda Function

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: my-lambda-function
  ZIP_FILE_NAME: lambda_function.zip

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt -t . ; fi

    - name: Package Lambda function
      run: zip -r9 $ZIP_FILE_NAME .

    - name: Deploy to Lambda
      uses: aws-actions/aws-cli@v1
      with:
        args: >
          lambda update-function-code 
          --function-name $LAMBDA_FUNCTION_NAME 
          --zip-file fileb://$ZIP_FILE_NAME
          --region $AWS_REGION
